- name: Deploy ACS on OCP Cluster
  import_tasks: deploy_acs.yml
  when: ocp4_aio_deploy_type == 'upi' or ocp4_aio_deploy_type == 'ipi'

- name: Deploy ACS on rhacm SNO Cluster
  import_tasks: deploy_acs_sno.yml
  when: ocp4_aio_deploy_type == 'sno'